/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ProdutoDAO;
import VO.Produto;
import banco.Banco;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Line
 */
public class ControlerProduto extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    
    //Criação dos Atributos 
    Banco bc = new Banco ("root", "", "localhost", "hotel", 3306);
    private ProdutoDAO produtoDao = new ProdutoDAO (bc);
    
    private Produto produtoVO;
    
            
            
    public ControlerProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadProduto = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        lblProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lblValorUnitario = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        lblProdConsumido = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtProdConsumido = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Produto");

        lblCadProduto.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblCadProduto.setText("Cadastro de Produto");

        lblCodigo.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblCodigo.setText("Código:");
        lblCodigo.setToolTipText("");

        lblProduto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblProduto.setText("Produto:");

        lblValorUnitario.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblValorUnitario.setText("Valor Unitário R$:");

        txtValorUnitario.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtValorUnitario.setBorder(null);

        lblQuantidade.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblQuantidade.setText("Quantidade: ");

        lblEstoque.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblEstoque.setText("Estoque:");

        lblProdConsumido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblProdConsumido.setText("Produto Consumido R$:");

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        txtProdConsumido.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtProdConsumido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        txtProdConsumido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdConsumidoActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cadastrar.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/deletar.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/menu.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fecharFormulario.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(lblCadProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblProduto)
                                .addGap(18, 18, 18)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValorUnitario)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnCadastrar)
                                .addGap(57, 57, 57)
                                .addComponent(btnAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblQuantidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(275, 275, 275)
                                        .addComponent(lblProdConsumido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProdConsumido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEstoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadProduto))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorUnitario)
                    .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblProdConsumido)
                                    .addComponent(txtProdConsumido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEstoque)))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdConsumidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdConsumidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdConsumidoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       
       ProdutoDAO produtoDAO= new ProdutoDAO();
        Produto produto1 = new Produto();

        if (txtCodigoProduto.getText().isEmpty() || txtProduto.getText().isEmpty()
                || txtQuantidade.getText().isEmpty() || txtEstoque.getText().isEmpty() || txtValorUnitario.getText().isEmpty() || 
                txtProdConsumido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Erro!! Por favor preencha os campos corretamente!!!");
        } else {

            produto1.setCodProduto(Integer.parseInt(txtCodigoProduto.getText()));
            produto1.setNomeProduto(txtProduto.getText());
            produto1.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
            produto1.setEstoque(Integer.parseInt(txtEstoque.getText()));
            produto1.setValorUnitario(Double.parseDouble(txtValorUnitario.getText()));
            produto1.setValorProdConsumido(Double.parseDouble(txtProdConsumido.getText()));
           
            produtoDAO.cadastrar(produto1);
            JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso!!!");
            //Limpa toda os campos da tela
            txtCodigoProduto.setText("");
            txtProduto.setText("");
            txtQuantidade.setText("");
            txtEstoque.setText("");
            txtValorUnitario.setText("");
            txtProdConsumido.setText("");
            
            //Volta o focus do mouse para o codigo Servico
            txtCodigoProduto.requestFocus();

        } 
      
                                    
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // Volta para a tela de Menu do Sistema
        Menu menu = new Menu();
        menu.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // Fecha todo o sistema quando vc clica!!!
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // Fecha apenas a tela atual
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try{
              if (txtCodigoProduto.getText().isEmpty()){
                  JOptionPane.showMessageDialog (rootPane, "Por favor, insira o código do produto para buscar os dados");
              }else{
                    produtoVO = new Produto ();
                    produtoVO = (Produto)produtoDao.buscar(Integer.parseInt(txtCodigoProduto.getText()));     
            if (produtoVO == null)
                JOptionPane.showMessageDialog (rootPane, "Produto não encontrado!!!");
            else{       
                txtProduto.setText(produtoVO.getNomeProduto());
                txtQuantidade.setText(String.format("%1", produtoVO.getQuantidade()));
                txtEstoque.setText(String.format("%1", produtoVO.getEstoque()));
                txtValorUnitario.setText("R$ " + String.format("%10.2f",produtoVO.getValorUnitario()) );
                txtProdConsumido.setText("R$ " + String.format("%10.2f",produtoVO.getValorProdConsumido()));
               
            }
    
        }
   

     }catch(HeadlessException | NumberFormatException e){
          

  JOptionPane.showMessageDialog (rootPane, "ERRO: " + e.getMessage());
       

 }


    
                                 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
      try{
            if (txtCodigoProduto.getText().isEmpty()){
                JOptionPane.showMessageDialog (rootPane, "Por favor, insira o código do produto!!!");
            }else{
                 produtoVO = new Produto ();
                 produtoVO = (Produto)produtoDao.buscar(Integer.parseInt(txtCodigoProduto.getText()));    
            if (produtoVO == null)         
                 JOptionPane.showMessageDialog (rootPane, "Registro não encontrado");
            else{
                 //Pergunta ao usuário se ele deseja deletar o registro.
            if(JOptionPane.showConfirmDialog(rootPane, "Deseja deletar o registro de " + produtoVO.getNomeProduto() + "(código do Produto:) "
                  + produtoVO.getCodProduto(), null, JOptionPane.YES_NO_OPTION)==0)
                {
           if(produtoDao.deletar(produtoVO)) //Verifica a existência de erros
                  JOptionPane.showMessageDialog (rootPane, "Registro deletado com êxito");
           else
                    JOptionPane.showMessageDialog (rootPane, "Não foi possível deletar o registro");
           }

  }
       
     }
     
   }catch(HeadlessException | NumberFormatException e){
          JOptionPane.showMessageDialog (rootPane, "ERRO: " + e.getMessage());

 }
  
                                              

    
                           
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
                                                    
       try{
            Produto produto = new Produto();
            ProdutoDAO produtoDAO = new ProdutoDAO(bc);
            produto = (Produto) produtoDAO.pesquisarCriterio("nome = '" + txtNome.getText() + "'");
      if (produto.getCodProduto() != 0) {
           if (txtNome.getText().isEmpty() || txtCpf.getText().isEmpty()
               || txtDataNascimento.getText().isEmpty() || txtIdade.getText().isEmpty()
               || txtSexo.getText().isEmpty() || txtEndereco.getText().isEmpty()
               || txtNumero.getText().isEmpty() || txtComplemento.getText().isEmpty()
               || txtCep.getText().isEmpty() || txtBairro.getText().isEmpty()
               || txtCidade.getText().isEmpty()  || txtEstado.getText().isEmpty()
               || txtUf.getText().isEmpty() || txtTelefone.getText().isEmpty()
               || txtCodigo.getText().isEmpty() || txtCargo.getText().isEmpty()
               || txtSetor.getText().isEmpty() || txtDataAdmissao.getText().isEmpty()
               || txtDataDemissao.getText().isEmpty() || txtSalario.getText().isEmpty()
               || txtLogin.getText().isEmpty()|| txtSenha.getText().isEmpty()) {
  
              JOptionPane.showMessageDialog(this, "É necessário alterar todos os campos");
   
         } else {
               
              produto.setCodProduto(Integer.parseInt(txtCodigo.getText ()));
              produto.setNome(txtNome.getText());
              produto.setCpf(txtCpf.getText());
              produto.setDataNascimento(txtDataNascimento.getText());
              produto.setIdade(Integer.parseInt(txtIdade.getText()));
              produto.setSexo((txtSexo.getText()));
              produto.setEndereco(txtEndereco.getText());
              produto.setNumero(Integer.parseInt(txtNumero.getText()));
              produto.setComplemento(txtComplemento.getText());
              produto.setCep(txtCep.getText());
              produto.setCidade(txtCidade.getText());
              produto.setEstado(txtEstado.getText());
              produto.setUf(txtUf.getText());
              produto.setTelefone(txtTelefone.getText());
              produto.setCargo(txtCargo.getText());
              produto.setSetor(txtSetor.getText());
              produto.setDataAdmissao(txtDataAdmissao.getText());
              produto.setDataDemissao(txtDataDemissao.getText());       
              produto.setSalario(Double.parseDouble(txtSalario.getText().replace(',', '.').replace('R', ' ').replace('$', ' ') ));
              produto.setLogin(txtLogin.getText());
              produto.setSenha(txtSenha.getText());

              ProdutoDAO dao = new ProdutoDAO(bc);
              dao.atualizar(produto);
             JOptionPane.showMessageDialog(this, "Dados do funcionário atualizado com sucesso! ");
  
          }
      
    } else {
          
          JOptionPane.showMessageDialog(this, "CPF inválido!");
       
      }
                
             

     }catch( HeadlessException | NumberFormatException e){
     
               JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
                }catch(Exception e){
               JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
         
       }
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlerProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlerProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlerProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlerProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlerProduto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCadProduto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblProdConsumido;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorUnitario;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtProdConsumido;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables
}
